#!/bin/sh

# hook up my "hear" to CCRMA
jack_connect Karl:receive_1 Max:in1

# hook up my "say" to CCRMA
jack_connect Max:out1 Karl:send_1

# so i can hear what i'm saying...
jack_connect Max:out1 system:playback_1

# so i can hear what they're saying (mono mix)
jack_connect Karl:receive_2 system:playback_2

